// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Url struct {
	ID        uuid.UUID
	ShortCode string
	LongUrl   string
	Clicks    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
