// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (id, short_code, long_url, clicks, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, short_code, long_url, clicks, created_at, updated_at
`

type CreateUrlParams struct {
	ID        uuid.UUID
	ShortCode string
	LongUrl   string
	Clicks    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createUrl,
		arg.ID,
		arg.ShortCode,
		arg.LongUrl,
		arg.Clicks,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByShortCode = `-- name: GetByShortCode :one
SELECT id, short_code, long_url, created_at, updated_at, clicks 
FROM urls 
WHERE short_code = $1
`

type GetByShortCodeRow struct {
	ID        uuid.UUID
	ShortCode string
	LongUrl   string
	CreatedAt time.Time
	UpdatedAt time.Time
	Clicks    int32
}

func (q *Queries) GetByShortCode(ctx context.Context, shortCode string) (GetByShortCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getByShortCode, shortCode)
	var i GetByShortCodeRow
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Clicks,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE urls SET clicks = clicks + 1, updated_at = NOW()
WHERE short_code = $1
`

func (q *Queries) IncrementClicks(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, incrementClicks, shortCode)
	return err
}
